apiVersion: v1
kind: Service
metadata:
  name: chat-frontend-svc
  namespace: personal-apps
  labels:
    app: chat-frontend
    app.kubernetes.io/name: chat-frontend
    app.kubernetes.io/part-of: chat-app
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app: chat-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
