apiVersion: v1
kind: Service
metadata:
  name: portfolio-svc
  namespace: personal-apps
  labels:
    app: portfolio
    app.kubernetes.io/name: portfolio
    app.kubernetes.io/part-of: personal-website
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app: portfolio
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
