apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    restartedAt: "2026-05-04T13:15:00Z"
  name: chat-backend
  namespace: personal-apps
  labels:
    app: chat-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-backend
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      containers:
        - name: chat-backend
          image: ghcr.io/1ashutoshverma/chat-app-backend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: chat-backend-secret
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /api
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api
              port: 8080
            initialDelaySeconds: 2
