apiVersion: v1
kind: Service
metadata:
  name: chat-backend-svc
  namespace: personal-apps
  labels:
    app: chat-backend
    app.kubernetes.io/name: chat-backend
    app.kubernetes.io/part-of: chat-app
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app: chat-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
